[constants]
reset_hour = 10
upload_dir = "uploads"
today_object_dir = "uploads/today"

# Define the unique set of objects (365+)
objects = [
    "A Vintage Car", "A Stone Bridge", "A Lonely Bench", "A Bird in Flight", 
    "A Colorful Wall", "A Towering Skyscraper", "A Quiet River", "An Old Clock",
    "A Spiral Staircase", "A Flower Petal", "A Piece of Street Art", "A Sunset",
    "A Reflection in a Puddle", "A Tree Silhouette", "A Cat in the Alley", "A Playground",
    "A Train Passing By", "A Church Steeple", "A Windmill", "A Ferris Wheel", "A Lighthouse",
    "A Street Lamp", "A Coffee Cup on a Table", "A Bookstore", "A Fruit Stand", "A Bicycle Basket",
    "A City Skyline", "A Horse in a Field", "A Seagull", "A Hot Air Balloon", "A Red Door",
    "A Snow-Capped Mountain", "A Blooming Flower", "A Piece of Driftwood", "A Historic Building",
    "A Crowded Market", "A Desert Landscape", "A Running Stream", "A Waterfall", "A Spider Web",
    "A Pebble Path", "A Greenhouse", "A Rowboat", "A Sandy Beach", "A Sailboat", "A Factory",
    "A Snowy Road", "A Lantern", "A Clock Tower", "A Dog Playing", "A Leaf in the Wind", 
    "A Quiet Alley", "A Skater in Motion", "A Rainbow", "A Butterfly", "A Hidden Doorway", 
    "A Bridge at Night", "A Starry Sky", "A Foggy Morning", 
    "A Raindrop on a Leaf", "A Glistening Spiderweb", "A Cracked Window", "A Wooden Fence"
]